### ISSUE TITLE
Question: repository

### ISSUE THREAD

**Issue by Keridos** [aureq/udoo-recipes#1]
Hi there,

Is it possible to use apt-get to install software in that installation that this tutorial describes? Or do I have to compile everything on my own?

**Comment by aureq** [comment]
@Keridos There's already a lot of software installed using the apt-get command. You will only have to recompile what's required.

**Comment by Keridos** [comment]
I just need Samba for now, so in case it is not installed, i can just apt-get install samba?

**Comment by aureq** [comment]
You answered your own question.
