### ISSUE TITLE
Missing include

### ISSUE THREAD

**Issue by Keridos** [aureq/udoo-recipes#3]
in part 3 you also need to copy kernel/include/linux/pxp_dma.h to the usr include folder, else the first 2 make commands fail due to it not being found.

**Comment by aureq** [comment]
@Keridos no you don't need to. I check my environment and xbmc-build/usr/include/linux is rather empty. Everything compiles fine without that header.

**Comment by Keridos** [comment]
Check the other thread please, I posted the error there.

**Comment by aureq** [comment]
@Keridos Here is a word of advice for you. I think it's great that you're reporting problems, but I think you can improve the way you report them. I invite you to read the following essay (pretty instructive).
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by Keridos** [comment]
Thanks for the link. But one thing to note for you aswell, please: You sent me back on my first issues that I did not correctly follow your tutorial without even checking what I wrote (at least for me it seemed that way). Although I asked you to try your tutorial on a fresh install (I had a fresh debian install 64bit inside a VM) and could reproduce every single problem I had.
Some of them seemed to be tied to the git repository for xbmc, so I will not blame you for that.
But you actually forgot some libraries for compiling xbmc (the configure script complains about them) and the pxp_dma.h file needed to be copied aswell for me, also reproducible by exactly following your tutorial.
I have managed to solve all the issues by hand until now, I suggest you change the link for the xbmc release to point to https://github.com/xbmc-imx6/xbmc, though.
That version compiled fine after I setup the missing dependencies. Had to copy one more header file to the xbmc root aswell in order to compile it correctly, think it was ipu.h.
And the only reason I opened another issue was to point towards the "try it yourself please" method.
But you might understand me being frustrated after you just closed my issues, told me to stick to your tutorial and that I was unable to follow simple instructions and then just disappeared for 11 (!) days.

**Comment by aureq** [comment]
@Keridos Look, it's the open-source world, and you're not willing to pay me with real money or bitcoin for any kind of support, I'd say you'd better use google and all the free resources of internet.

**Comment by Keridos** [comment]
I do know its the opensource world, but I tried googling my issues BEFORE I opened them here.
Somehow I expect a guide to be updated, when it is necessary though. If you checked on github in my profile, I do even have my own opensource project and I do participate in some more aswell. And you did some small mistake again: You said I was not willing to pay you for your work: That is not true. See, I like the idea of crowdfunding and donations even for free/opensource software, so I do not have any problem with that. But as I already stated, I somehow did not feel like you were taking me seriously.

**Comment by aureq** [comment]
1. Wait for the next version
   - cmake is fixed, 
   - the pxp_dma.h was part of a broader problem
2. Do not expect, be proactive
3. No one will ever take you seriously if you create more than 1 issue for the same problem (and the worst of all was #6)

**Comment by Keridos** [comment]
Small hint: The posts I criticised were posted A LOT earlier than issue #6.....
I was active, I pretty much solved all issues on my own until now. But since you turned down my pull requests (which meant I was proactive), I did not mention my other problems here anymore.

**Comment by aureq** [comment]
+1
So why are you continuing this conversation then ?

**Comment by Keridos** [comment]
Thanks for this tutorial anyway though, It helped me a lot with making the image. So keep up the good work, but maybe try to be a bit more sensitive when answering issues.

**Comment by aureq** [comment]
Thank you, this is all I wanted to read. and yes, I will try.

To give you the prime info.
1. brand new dev env, so all missing deps should be there
2. support for the wandboard quad
3. (hopefully) latest kernel, uboo and latest freescale libs
4. latest xbmc 13.1 with imx6 support

**Comment by Keridos** [comment]
After trying a bit I can tell that the xbmc fork I posted works pretty good, I just used the master branch of it. Just the few dependencies for the build environment and the rootfs (decoding mp3 and mpeg, f.ex) were needed for compiling/running. Hardware acceleration seems to work flawlessly on the udoo-quad, was able to play everything I threw at it (even high bitrate HD videos) without lag.
