### ISSUE TITLE
XMBC Compilation Errors

### ISSUE THREAD

**Issue by Keridos** [aureq/udoo-recipes#4]
You need to copy lib/taglib/Makefile to lib/taglib/taglib-1.8/build before running make -C lib/taglib else it fails due to no makefile being found.
ALso you need to apt-get install cmake. Maybe you missed that in the setup commands for the environment.

**Comment by Keridos** [comment]
Btw: I get  a "platform not recognized" from eglvivante.h, what causes this?

**Comment by aureq** [comment]
I think your issue is because you're using cmake and not gnu make (make). Same as issue #3, cmake is not installed in my environment and it works like a charm.

**Comment by aureq** [comment]
@Keridos you must ensure you installed gcc-4.7-arm-linux-gnueabihf and like packages if you want this to work.

**Comment by Keridos** [comment]
I am using debian 7.5 amd 64 in a VM, i have the gnuabihf things installed.
Maybe the git repository for XBMC changed?
That was a fresh debian 7 install and I followed your instructions step by step and encountered the problems i mentioned.

Freescale errors at make, you see it really wants pxp_dma.h and XBMC fails due to "platform not recognized":

```
# make PLATFORM=IMX6Q C_INCLUDE_PATH=/usr/src/linux/include/ all
/usr/bin/make -C hdmi-cec all
make[1]: Entering directory `/root/work/freescale/imx-lib-3.5.7-1.0.0/hdmi-cec'
gcc -DIMX6Q -Wall -O2 -fPIC -c mxc_hdmi-cec.c -o mxc_hdmi-cec.o
gcc -shared -nostartfiles -Wl,-soname,libcec.so.1 mxc_hdmi-cec.o -o libcec.so.1
ln -s libcec.so.1 libcec.so
ar -rc libcec.a  mxc_hdmi-cec.o
make[1]: Leaving directory `/root/work/freescale/imx-lib-3.5.7-1.0.0/hdmi-cec'
/usr/bin/make -C ipu all
make[1]: Entering directory `/root/work/freescale/imx-lib-3.5.7-1.0.0/ipu'
gcc -DIMX6Q  -Wall -O2 -fPIC -c mxc_ipu_hl_lib_dummy.c -o mxc_ipu_hl_lib_dummy.o
gcc -shared -nostartfiles -Wl,-soname,libipu.so.0 -o libipu.so.0 mxc_ipu_hl_lib_dummy.o -lpthread
ln -s libipu.so.0 libipu.so
make[1]: Leaving directory `/root/work/freescale/imx-lib-3.5.7-1.0.0/ipu'
/usr/bin/make -C pxp all
make[1]: Entering directory `/root/work/freescale/imx-lib-3.5.7-1.0.0/pxp'
gcc -DIMX6Q  -Wall -O2 -fPIC -c pxp_lib.c -o pxp_lib.o
In file included from pxp_lib.c:25:0:
pxp_lib.h:19:27: fatal error: linux/pxp_dma.h: No such file or directory
compilation terminated.
make[1]: *** [pxp_lib.o] Error 1
make[1]: Leaving directory `/root/work/freescale/imx-lib-3.5.7-1.0.0/pxp'
make: *** [pxp] Error 2
```

**Comment by Keridos** [comment]
No idea what could cause that?
I made a fresh debian install in a VM and just got these issues after following your steps, I made sure everything was installed correctly.

**Comment by aureq** [comment]
So, you're having an issue in compiling a freescale library ? I'm sure before asking me you kindly requested some help from the freescale guys and its community ?
I mean, I'm sure if that's a common problem someone has already found a solution to this and already reported it.

**Comment by Keridos** [comment]
The latest issue i had was my java failing for some reason and getting a segfault, upgrading to java 7 solved that after a few tries.
