### ISSUE TITLE
Quite some issues

### ISSUE THREAD

**Issue by Keridos** [aureq/udoo-recipes#6]
Can you do me the favor and recreate your workspace with the commands you describe here? I'm 99% sure that you will run into the same problem I ran into when you do that.
I exactly followed all orders you did and had a few missing libraries, needed to copy one more header file. I think that is due to some new stuff in the code of the github repos since you made the tutorial. I am pretty much still trying to figure out what I need to do to be able to compile xbmc.

**Comment by aureq** [comment]
@Keridos You do realise that opening a new issue as a way to request assistance is not appropriate, right ?
